version: "3"
services: 
  web:
    container_name: web
    image: nginx:latest
    ports:
      - "8080:80"
    volumes: 
      - ./code:/code
      - ./page.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - default
  php-fpm:
    container_name: php-fpm
    image: php:7-fpm
    volumes:
        - ./code:/code
    networks:
      - default